### ISSUE TITLE
Jobs that time out are not correctly updated on the webpage

### ISSUE THREAD

**Issue by koalaspirit** [Computational-Plant-Science/plantit#49] opened 2020-11-20 11:28 UTC
See Job 6850988 on stampede2 (PlantIT ID: 1605842632). The job hit the wall time limit but shows up as running on the webpage

**Comment by w-bonelli** [comment] 2020-11-23 16:01
Duplicate of #48

**Closed by w-bonelli** 2020-11-23 16:01 UTC
